/*
 * This file is generated by jOOQ.
 */
package generatedEntities;


import generatedEntities.tables.FlywaySchemaHistory;
import generatedEntities.tables.Organisation;
import generatedEntities.tables.Product;
import generatedEntities.tables.Receipt;
import generatedEntities.tables.ReceiptItem;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.organisation</code>.
     */
    public final Organisation ORGANISATION = Organisation.ORGANISATION;

    /**
     * The table <code>public.product</code>.
     */
    public final Product PRODUCT = Product.PRODUCT;

    /**
     * The table <code>public.receipt</code>.
     */
    public final Receipt RECEIPT = Receipt.RECEIPT;

    /**
     * The table <code>public.receipt_item</code>.
     */
    public final ReceiptItem RECEIPT_ITEM = ReceiptItem.RECEIPT_ITEM;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY,
            Organisation.ORGANISATION,
            Product.PRODUCT,
            Receipt.RECEIPT,
            ReceiptItem.RECEIPT_ITEM
        );
    }
}
