/*
 * This file is generated by jOOQ.
 */
package generatedEntities;


import generatedEntities.tables.FlywaySchemaHistory;
import generatedEntities.tables.Organisation;
import generatedEntities.tables.Product;
import generatedEntities.tables.Receipt;
import generatedEntities.tables.ReceiptItem;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.organisation</code>.
     */
    public static final Organisation ORGANISATION = Organisation.ORGANISATION;

    /**
     * The table <code>public.product</code>.
     */
    public static final Product PRODUCT = Product.PRODUCT;

    /**
     * The table <code>public.receipt</code>.
     */
    public static final Receipt RECEIPT = Receipt.RECEIPT;

    /**
     * The table <code>public.receipt_item</code>.
     */
    public static final ReceiptItem RECEIPT_ITEM = ReceiptItem.RECEIPT_ITEM;
}
