/*
 * This file is generated by jOOQ.
 */
package generatedEntities;


import generatedEntities.tables.Company;
import generatedEntities.tables.FlywaySchemaHistory;
import generatedEntities.tables.Product;
import generatedEntities.tables.Role;
import generatedEntities.tables.UserRole;
import generatedEntities.tables.Users;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.company</code>.
     */
    public static final Company COMPANY = Company.COMPANY;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.product</code>.
     */
    public static final Product PRODUCT = Product.PRODUCT;

    /**
     * The table <code>public.role</code>.
     */
    public static final Role ROLE = Role.ROLE;

    /**
     * The table <code>public.user_role</code>.
     */
    public static final UserRole USER_ROLE = UserRole.USER_ROLE;

    /**
     * The table <code>public.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
