/*
 * This file is generated by jOOQ.
 */
package generatedEntities.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ReceiptItem implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Integer id;
    private final Integer receiptId;
    private final Integer productCode;
    private final Integer price;
    private final Integer amount;

    public ReceiptItem(ReceiptItem value) {
        this.id = value.id;
        this.receiptId = value.receiptId;
        this.productCode = value.productCode;
        this.price = value.price;
        this.amount = value.amount;
    }

    public ReceiptItem(
        Integer id,
        Integer receiptId,
        Integer productCode,
        Integer price,
        Integer amount
    ) {
        this.id = id;
        this.receiptId = receiptId;
        this.productCode = productCode;
        this.price = price;
        this.amount = amount;
    }

    /**
     * Getter for <code>public.receipt_item.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Getter for <code>public.receipt_item.receipt_id</code>.
     */
    public Integer getReceiptId() {
        return this.receiptId;
    }

    /**
     * Getter for <code>public.receipt_item.product_code</code>.
     */
    public Integer getProductCode() {
        return this.productCode;
    }

    /**
     * Getter for <code>public.receipt_item.price</code>.
     */
    public Integer getPrice() {
        return this.price;
    }

    /**
     * Getter for <code>public.receipt_item.amount</code>.
     */
    public Integer getAmount() {
        return this.amount;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final ReceiptItem other = (ReceiptItem) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.receiptId == null) {
            if (other.receiptId != null)
                return false;
        }
        else if (!this.receiptId.equals(other.receiptId))
            return false;
        if (this.productCode == null) {
            if (other.productCode != null)
                return false;
        }
        else if (!this.productCode.equals(other.productCode))
            return false;
        if (this.price == null) {
            if (other.price != null)
                return false;
        }
        else if (!this.price.equals(other.price))
            return false;
        if (this.amount == null) {
            if (other.amount != null)
                return false;
        }
        else if (!this.amount.equals(other.amount))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.receiptId == null) ? 0 : this.receiptId.hashCode());
        result = prime * result + ((this.productCode == null) ? 0 : this.productCode.hashCode());
        result = prime * result + ((this.price == null) ? 0 : this.price.hashCode());
        result = prime * result + ((this.amount == null) ? 0 : this.amount.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ReceiptItem (");

        sb.append(id);
        sb.append(", ").append(receiptId);
        sb.append(", ").append(productCode);
        sb.append(", ").append(price);
        sb.append(", ").append(amount);

        sb.append(")");
        return sb.toString();
    }
}
