/*
 * This file is generated by jOOQ.
 */
package generatedEntities.tables.pojos;


import java.io.Serializable;
import java.time.LocalDate;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Receipt implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Integer id;
    private final LocalDate creationDate;
    private final Long organisationTaxNumber;

    public Receipt(Receipt value) {
        this.id = value.id;
        this.creationDate = value.creationDate;
        this.organisationTaxNumber = value.organisationTaxNumber;
    }

    public Receipt(
        Integer id,
        LocalDate creationDate,
        Long organisationTaxNumber
    ) {
        this.id = id;
        this.creationDate = creationDate;
        this.organisationTaxNumber = organisationTaxNumber;
    }

    /**
     * Getter for <code>public.receipt.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Getter for <code>public.receipt.creation_date</code>.
     */
    public LocalDate getCreationDate() {
        return this.creationDate;
    }

    /**
     * Getter for <code>public.receipt.organisation_tax_number</code>.
     */
    public Long getOrganisationTaxNumber() {
        return this.organisationTaxNumber;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Receipt other = (Receipt) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.creationDate == null) {
            if (other.creationDate != null)
                return false;
        }
        else if (!this.creationDate.equals(other.creationDate))
            return false;
        if (this.organisationTaxNumber == null) {
            if (other.organisationTaxNumber != null)
                return false;
        }
        else if (!this.organisationTaxNumber.equals(other.organisationTaxNumber))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.creationDate == null) ? 0 : this.creationDate.hashCode());
        result = prime * result + ((this.organisationTaxNumber == null) ? 0 : this.organisationTaxNumber.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Receipt (");

        sb.append(id);
        sb.append(", ").append(creationDate);
        sb.append(", ").append(organisationTaxNumber);

        sb.append(")");
        return sb.toString();
    }
}
