/*
 * This file is generated by jOOQ.
 */
package generatedEntities.tables.records;


import generatedEntities.tables.ReceiptItem;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ReceiptItemRecord extends UpdatableRecordImpl<ReceiptItemRecord> implements Record5<Integer, Integer, Integer, Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.receipt_item.id</code>.
     */
    public ReceiptItemRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.receipt_item.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.receipt_item.receipt_id</code>.
     */
    public ReceiptItemRecord setReceiptId(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.receipt_item.receipt_id</code>.
     */
    public Integer getReceiptId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.receipt_item.product_code</code>.
     */
    public ReceiptItemRecord setProductCode(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.receipt_item.product_code</code>.
     */
    public Integer getProductCode() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.receipt_item.price</code>.
     */
    public ReceiptItemRecord setPrice(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.receipt_item.price</code>.
     */
    public Integer getPrice() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.receipt_item.amount</code>.
     */
    public ReceiptItemRecord setAmount(Integer value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.receipt_item.amount</code>.
     */
    public Integer getAmount() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, Integer, Integer, Integer, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, Integer, Integer, Integer, Integer> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return ReceiptItem.RECEIPT_ITEM.ID;
    }

    @Override
    public Field<Integer> field2() {
        return ReceiptItem.RECEIPT_ITEM.RECEIPT_ID;
    }

    @Override
    public Field<Integer> field3() {
        return ReceiptItem.RECEIPT_ITEM.PRODUCT_CODE;
    }

    @Override
    public Field<Integer> field4() {
        return ReceiptItem.RECEIPT_ITEM.PRICE;
    }

    @Override
    public Field<Integer> field5() {
        return ReceiptItem.RECEIPT_ITEM.AMOUNT;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getReceiptId();
    }

    @Override
    public Integer component3() {
        return getProductCode();
    }

    @Override
    public Integer component4() {
        return getPrice();
    }

    @Override
    public Integer component5() {
        return getAmount();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getReceiptId();
    }

    @Override
    public Integer value3() {
        return getProductCode();
    }

    @Override
    public Integer value4() {
        return getPrice();
    }

    @Override
    public Integer value5() {
        return getAmount();
    }

    @Override
    public ReceiptItemRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public ReceiptItemRecord value2(Integer value) {
        setReceiptId(value);
        return this;
    }

    @Override
    public ReceiptItemRecord value3(Integer value) {
        setProductCode(value);
        return this;
    }

    @Override
    public ReceiptItemRecord value4(Integer value) {
        setPrice(value);
        return this;
    }

    @Override
    public ReceiptItemRecord value5(Integer value) {
        setAmount(value);
        return this;
    }

    @Override
    public ReceiptItemRecord values(Integer value1, Integer value2, Integer value3, Integer value4, Integer value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ReceiptItemRecord
     */
    public ReceiptItemRecord() {
        super(ReceiptItem.RECEIPT_ITEM);
    }

    /**
     * Create a detached, initialised ReceiptItemRecord
     */
    public ReceiptItemRecord(Integer id, Integer receiptId, Integer productCode, Integer price, Integer amount) {
        super(ReceiptItem.RECEIPT_ITEM);

        setId(id);
        setReceiptId(receiptId);
        setProductCode(productCode);
        setPrice(price);
        setAmount(amount);
    }

    /**
     * Create a detached, initialised ReceiptItemRecord
     */
    public ReceiptItemRecord(generatedEntities.tables.pojos.ReceiptItem value) {
        super(ReceiptItem.RECEIPT_ITEM);

        if (value != null) {
            setId(value.getId());
            setReceiptId(value.getReceiptId());
            setProductCode(value.getProductCode());
            setPrice(value.getPrice());
            setAmount(value.getAmount());
        }
    }
}
